---
sidebar: docs_sidebar 
permalink: docs/rn_whatsnew.html 
summary: このバージョンの NetApp HCI の新機能について説明します。 
keywords: netapp, hci, element, new, whatsnew 
---
= NetApp HCI の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element


[role="lead"]
ネットアップでは、 NetApp HCI を定期的に更新して、新機能、拡張機能、およびバグ修正を提供しています。NetApp HCI 1.8P1 には、ストレージクラスタ用の Element 12.2 が含まれています。

* 。 <<NetApp HCI 1.8P1>> セクションでは、 NetApp HCI バージョン 1.8P1 の新機能とアップデートについて説明します。
* 。 <<Element 12.2>> ここでは、 NetApp Element 12.2 の新機能とアップデートについて説明します。




== NetApp HCI 1.8P1

NetApp HCI 1.8P1 では、セキュリティと安定性が向上しています。



=== NetApp HCI ドキュメントの機能拡張

NetApp HCI のアップグレード、拡張、監視、および概念の情報に、わかりやすい形式でアクセスできるようになりました link:index.html["こちらをご覧ください"^]。



=== NetApp Element Plug-in for vCenter Server 4.5 の可用性

NetApp Element Plug-in for vCenter Server 4.5 は、管理ノード 12.2 および NetApp HCI 1.8P1 リリースでは使用できません。プラグインをアップグレードするには、の手順に従います link:concept_hci_upgrade_overview.html["NetApp HCI のアップグレード"^] ドキュメント



=== NetApp Hybrid Cloud Control の機能拡張

NetApp Hybrid Cloud Control はバージョン 1.8P1 で強化されています。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["詳細はこちら。"^]。



== Element 12.2

NetApp HCI 1.8P1 には、ストレージクラスタ用の Element 12.2 が含まれています。Element 12.2 では、 SolidFire エンタープライズ SDS 、保存中のソフトウェア暗号化、メンテナンスモード、ボリュームアクセスセキュリティの強化、 UI への Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）アクセス、ストレージノードのファームウェアの更新、およびセキュリティの更新が導入されています。



=== SolidFire エンタープライズ SDS

Element 12.2 では、 SolidFire エンタープライズ SDS （ ESDS ）が導入されています。SolidFire ESDS には、 SolidFire スケールアウトテクノロジと NetApp Element ソフトウェアデータサービスの利点があり、 SolidFire ESDS のリファレンス構成を満たす任意のハードウェア上にあります。 http://docs.netapp.com/sfe-122/index.jsp?topic=%2Fcom.netapp.doc.sfe-sds-ig%2FGUID-F1BDD19F-AF33-4CDE-B67F-C5E17D4E6DE9.html["詳細はこちら。"^]。

SolidFire に関連する新しい Element API メソッドは次のとおりです ESDS (http://docs.netapp.com/sfe-122/index.jsp?topic=%2Fcom.netapp.doc.sfe-sds-ug%2FGUID-4D335B61-6B68-4B81-AD6E-BCA1E7ABACD5.html["SolidFire ESDS の Element 12.2 API 情報"] 詳細については、を参照してください）。

* 「 GetLicenseKey 」をクリックします
* 'setLicenseKey'




=== ソフトウェアによる保存データの暗号化

Element 12.2 では、保存データのソフトウェア暗号化が導入されています。これは、ストレージクラスタを作成すると有効になります（ SolidFire エンタープライズ SDS ストレージクラスタを作成するとデフォルトで有効になります）。この機能では、ストレージノード内の SSD に格納されているすべてのデータが暗号化され、クライアント IO のパフォーマンスへの影響は非常に小さく（最大 2% ）すぎません。

ソフトウェア暗号化に関連する Element API メソッドは次のとおりです 休眠状態（ http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/home.html["Element API リファレンスガイド』を参照してください"^] 詳細については、を参照してください）。

* 'CreateCluster'




=== メンテナンスモード

Element 12.2 では、メンテナンスモードが導入されています。このモードでは、ソフトウェアのアップグレードやホストの修復などのメンテナンスのためにストレージノードをオフラインにして、すべてのデータを完全に同期できなくなります。メンテナンスが必要なノードがある場合は、開始前にそれらのノードのメンテナンスモードを有効にすることで、ストレージクラスタの残りのノードへの I/O の影響を最小限に抑えることができます。メンテナンスモードは、アプライアンスノードと SolidFire ESDS ノードの両方で使用できます。



=== ボリュームアクセスのセキュリティの強化

VLAN （仮想ネットワーク）の関連付けに基づいて、特定のイニシエータへのボリュームアクセスを制限できるようになりました。新規または既存のイニシエータを 1 つ以上の仮想ネットワークに関連付けて、そのイニシエータをこれらの仮想ネットワーク経由でアクセス可能な iSCSI ターゲットに制限できます。

これらに関連する Element API メソッドは次のとおりです セキュリティの向上（ http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/home.html["Element API リファレンスガイド』を参照してください"^] 詳細については、を参照してください）。

* 「 CreateInitiators 」を参照してください
* 「 modifyInitiators 」
* 「アカウントの追加」
* 「ディレクトリアカウント」




=== UI への Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）アクセス

Element 12.2 では、 FQDN を使用したクラスタ Web インターフェイスアクセスがサポートされます。Element 12.2 ストレージクラスタで、 FQDN を使用して Element Web UI 、ノード UI 、管理ノード UI などの Web ユーザインターフェイスにアクセスする場合は、最初にストレージクラスタ設定を追加して、クラスタで使用される FQDN を特定する必要があります。この設定を行うと、クラスタはログインセッションを適切にリダイレクトできるようになり、キー管理ツールやアイデンティティプロバイダなどの外部サービスとの統合を強化して多要素認証に対応できます。この機能を使用するには、管理サービスバージョン 2.15 以降が必要です。 link:task_nde_access_ui_fqdn.html["詳細はこちら。"^]。



=== ストレージノードのファームウェアの更新

Element 12.2 では、ストレージノード用のファームウェアの更新が含まれています。 http://docs.netapp.com/us-en/hci/docs/rn_relatedrn.html["詳細はこちら。"^]。



=== セキュリティの機能拡張

Element 12.2 では、ストレージノードおよび管理ノードのセキュリティの脆弱性を解決します。 http://security.netapp.com/["詳細はこちら。"^] これらのセキュリティ機能拡張について



=== ドライブに障害が発生した場合の新しい SMART 警告

Element 12.2 では、ドライブの SMART ヘルスデータを使用して、 SolidFire アプライアンスドライブに対して定期的な健全性チェックを実行するようになりました。SMART ヘルスチェックに失敗したドライブは、障害に近い可能性があります。ドライブが SMART ヘルスチェックに失敗した場合、重大度が「 D rive with serial ： <serial number> in slot ： <node slot><drive slot> has failed the Smart overall health check. 」という新しいクラスタエラーが表示されます。この問題を解決するには ' ドライブを交換してください

[discrete]
== 詳細については、こちらをご覧ください

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["『 NetApp Hybrid Cloud Control and Management Services Release Notes 』を参照してください"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI のリソースページ"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["NetApp HCI および NetApp Element のファームウェアとドライバのバージョン ソフトウェア"^]

