---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_element_software.html 
summary: NetApp HCI システムのアップグレードの一環として、 NetApp Element ソフトウェアをアップグレードします。 
keywords: netapp, hci, cluster, element, H610S upgrade, hcc 
---
= Element ソフトウェアをアップグレードします
:allow-uri-read: 


[role="lead"]
NetApp Element ソフトウェアをアップグレードするには、NetApp Hybrid Cloud ControlのUIまたはREST APIを使用します。Element ソフトウェアのアップグレードの実行中は、ノードの追加と削除、ドライブの追加と削除、イニシエータ、ボリュームアクセスグループ、仮想ネットワークに関連するコマンドなど、一部の処理は実行できません。


NOTE: Element 12.5以降では、ElementソフトウェアのアップグレードでNetApp HealthToolsがサポートされなくなりました。Element 11.0または11.1を実行している場合は、最初にが必要です link:https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["HealthToolsを使用してElement 12.3にアップグレードします"^] NetApp Hybrid Cloud Controlを使用してElement 12.5にアップグレードします。

.必要なもの
* * admin 権限 * ：アップグレードを実行する権限がストレージクラスタ管理者に付与されています。
* * 有効なアップグレードパス * ：アップグレード先の Element バージョンのアップグレードパス情報を確認し、アップグレードパスが有効であることを確認しておきます。https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["ネットアップの技術情報： NetApp Element ソフトウェアを実行するストレージクラスタのアップグレードマトリックス"^]
* * システム時間の同期 * ：すべてのノードのシステム時間が同期されており、 NTP がストレージクラスタとノードに対して正しく設定されていることを確認しておきます。各ノードには、ノード Web UI （「 https://[IP address 」： 442 ）に DNS ネームサーバを設定する必要があります。時刻のずれに関連する未解決のクラスタ障害はありません。
* * システムポート * ： NetApp Hybrid Cloud Control をアップグレードに使用している場合は、必要なポートが開いていることを確認しておきます。を参照してください link:hci_prereqs_required_network_ports.html["ネットワークポート"] を参照してください。
* * 管理ノード * ： NetApp Hybrid Cloud Control の UI および API では、環境内の管理ノードはバージョン 11.3 を実行しています。
* * 管理サービス * ：管理サービスバンドルを最新バージョンに更新しました。



IMPORTANT: Elementソフトウェアをバージョン12.5にアップグレードする前に、最新の管理サービスバンドルにアップグレードする必要があります。Elementソフトウェアをバージョン12.5に更新する場合は、管理サービス2.20.69以降が必要です。

* * クラスタの健全性 * ：クラスタをアップグレードする準備が完了していることを確認しました。を参照してください link:task_hcc_upgrade_element_prechecks.html["ストレージをアップグレードする前に、 Element ストレージの健全性チェックを実行します"]。
* * H610Sノードのベースボード管理コントローラ（BMC）を更新*：H610SノードのBMCバージョンをアップグレードしました。を参照してください link:rn_H610S_BMC_3.84.07.html["リリースノートおよびアップグレード手順"]。
* *アップグレード処理時間*:アップグレードを実行するための十分な時間を確保しています。Elementソフトウェア12.5にアップグレードする場合、アップグレードプロセスの時間は、Elementソフトウェアの現在のバージョンとファームウェアの更新によって異なります。
+
[cols="20,20,20,20,20"]
|===
| ストレージノード | Elementソフトウェアの現在のバージョン | ノードあたりのソフトウェアとファームウェアのインストール時間の概算。^1 ^ | ノードあたりのおおよそのデータ同期時間^2^ | ノードあたりのアップグレード時間の概算 


| 最新のファームウェアを搭載したSolidFire およびNetApp Hシリーズのすべてのノード | 12.x | 15 分 | 10～15分 | 20～30分 


| H610SとH410S | 12.xおよび11.8 | 60分 | 30～60分 | 90～120分 


| H610S | 11.7以前 | 90分 | 40～70分 | 130～160分も必要です https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["ノードの完全なシャットダウンと電源切断を実行します"^] H610Sノードごとに、 
|===
+
^1ご使用のハードウェアのファームウェアおよびドライバファームウェアの完全なマトリックスについては、こちらを参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["こちらの技術情報アーティクル"^] （ログインが必要です）。

+
^2^クラスタに高い書き込みIOPSの負荷があり、ファームウェアの更新時間が長い場合、データの同期時間が長くなります。

* *エンドユーザライセンス契約（EULA）*：管理サービス2.20以降では、NetApp Hybrid Cloud ControlのUIまたはAPIを使用してElementソフトウェアをアップグレードする前に、EULAに同意して保存する必要があります。
+
.. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
.. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
.. インターフェイスの右上にある [* Upgrade] を選択します。
.. EULAがポップアップ表示されます。下にスクロールして、[現在および今後のすべての更新を許可する*]を選択し、[保存*]を選択します。
+

NOTE: EULAに同意すると、以後のすべての更新についてそのEULAが記録され、自動ダウンロード機能が有効になります。ネットアップのソフトウェアの更新とアップグレードに関する最新情報が提供されます。この情報はお客様の自由裁量と利便性に基づいてインストールすることができます。ネットアップオンラインソフトウェアリポジトリへのネットワーク接続を無効にすることで、自動ダウンロード機能を無効にできます。





次のいずれかの Element ソフトウェアアップグレードオプションを選択します。

* <<Use NetApp Hybrid Cloud Control UI to upgrade Element storage>>
* <<Use NetApp Hybrid Cloud Control API to upgrade Element storage>>



IMPORTANT: H610SシリーズノードをElement 12.5にアップグレードする場合、ノードで11.8よりも前のバージョンのElementソフトウェアが実行されているときは、こので追加のアップグレード手順を実行する必要があります https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["こちらの技術情報アーティクル"^] ストレージノードごとに割り当てます。Element 11.8以降を実行している場合は、追加のアップグレード手順は必要ありません。



== NetApp Hybrid Cloud Control UI を使用して Element ストレージをアップグレードします

NetApp Hybrid Cloud Control の UI を使用して、ストレージクラスタをアップグレードできます。

管理ノードがインターネットに接続されていない場合は、をダウンロードしておきます https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["NetApp HCI ストレージクラスタ用の NetApp HCI ソフトウェアパッケージ"^]。


CAUTION: NetApp Hybrid Cloud Controlを使用してストレージクラスタをアップグレードする際の潜在的な問題とその対処方法については、このドキュメントを参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["こちらの技術情報アーティクル"^]。

.手順
. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上にある [* Upgrade] を選択します。
. [* Upgrades] ページで、 [* Storage] を選択します。
+
[* ストレージ * ] タブには、インストールの一部であるストレージクラスタが一覧表示されます。NetApp Hybrid Cloud Control からクラスタにアクセスできない場合は、 * Upgrades * ページに表示されません。

. 次のオプションを選択し、クラスタに該当する一連の手順を実行します。
+
[cols="2*"]
|===
| オプション | 手順 


| 管理ノードに外部接続が必要です。  a| 
.. アップグレードするクラスタの横にあるドロップダウン矢印を選択し、 * Element * タブで利用可能なアップグレードバージョンから選択します。
.. [* アップグレードの開始 * ] を選択します。



TIP: アップグレード中は、アップグレードステータス * が変更され、プロセスのステータスが反映されます。また、アップグレードの一時停止など、実行する操作に応じて変更が加えられたか、またはアップグレードでエラーが返された場合も変更されます。を参照してください <<Upgrade status changes>>。


NOTE: アップグレードの実行中は、ページを離れてあとから表示し、進捗状況の監視を続行できます。クラスタの行が折りたたまれている場合、ページではステータスと現在のバージョンは動的に更新されません。表を更新するには、クラスタの行を展開する必要があります。また、ページを更新することもできます。

アップグレードの完了後にログをダウンロードできます。



| 外部に接続されていないダークサイトに管理ノードが配置されている。  a| 
.. [* Browse] を選択して、ダウンロードしたアップグレード・パッケージをアップロードします。
.. アップロードが完了するまで待ちます。進捗バーにアップロードのステータスが表示されます。



CAUTION: ブラウザウィンドウから別の場所に移動すると、ファイルのアップロードが失われます。

ファイルのアップロードと検証が完了すると、画面にメッセージが表示されます。検証には数分かかることがあります。この段階でブラウザウィンドウから移動しても、ファイルのアップロードは維持されます。



| Element 11.8 より前のバージョンを実行している H610S クラスタをアップグレードしています。  a| 
.. アップグレードするクラスタの横にあるドロップダウン矢印を選択し、アップグレード可能なバージョンから選択します。
.. [* アップグレードの開始 * ] を選択します。アップグレードが完了すると、追加のアップグレード手順を実行するように求められます。
.. に必要な追加の手順を実行します https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["こちらの技術情報アーティクル"^]をクリックし、完了したことをUIで確認します。


アップグレードの完了後にログをダウンロードできます。アップグレードステータスのさまざまな変更については、を参照してください <<Upgrade status changes>>。

|===




=== アップグレードステータスが変わります

アップグレードプロセスの実行前、実行中、実行後に、 UI の * アップグレードステータス * 列に表示されるさまざまな状態を以下に示します。

[cols="2*"]
|===
| アップグレードの状態 | 説明 


| 最新 | クラスタが最新の Element バージョンにアップグレードされました。 


| 使用可能なバージョン | Element / ストレージファームウェアの新しいバージョンをアップグレードできます。 


| 実行中です | アップグレードを実行中です。進行状況バーにアップグレードステータスが表示されます。画面にはノードレベルの障害も表示され、アップグレードの進行に伴いクラスタ内の各ノードのノード ID も表示されます。各ノードのステータスは、 Element UI または NetApp Element Plug-in for vCenter Server UI を使用して監視できます。 


| Pausing をアップグレードします | アップグレードを一時停止することもできます。アップグレードプロセスの状態によっては、一時停止処理が成功するか失敗するかが決まります。一時停止処理の確認を求める UI プロンプトが表示されます。アップグレードを一時停止する前にクラスタが安全な場所にあることを確認するには、アップグレード処理が完全に一時停止されるまでに最大 2 時間かかることがあります。アップグレードを再開するには、 * Resume * （続行）を選択します。 


| 一時停止中 | アップグレードを一時停止した。[* Resume （続行） ] を選択して、プロセスを再開します。 


| エラー | アップグレード中にエラーが発生しました。エラーログをダウンロードして、ネットアップサポートに送信できます。エラーを解決したら、ページに戻って * Resume * （続行）を選択します。アップグレードを再開すると、システムが健全性チェックを実行してアップグレードの現在の状態を確認している間、進捗状況バーが数分間後方に移動します。 


| 検出できません | オンラインのソフトウェアリポジトリにアクセスするための外部接続がない場合、 NetApp Hybrid Cloud Control では、バージョンを利用可能 * ではなくこのステータスが表示されます。外部接続を確立してもこのメッセージが表示される場合は、を確認してください link:task_mnode_configure_proxy_server.html["プロキシ設定："]。 


| フォローアップを完了します | H610S ノードを 11.8 より前のバージョンからアップグレードした場合のみアップグレードプロセスのフェーズ1が完了すると、追加のアップグレード手順を実行するように求められます（を参照） https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["こちらの技術情報アーティクル"^]）。これらの追加手順を完了し、完了したことを確認すると、ステータスが*最新*に変わります。 
|===


== NetApp Hybrid Cloud Control API を使用して Element ストレージをアップグレードします

API を使用して、クラスタ内のストレージノードを最新バージョンの Element ソフトウェアにアップグレードできます。API の実行には、任意の自動化ツールを使用できます。ここで説明する API ワークフローでは、例として管理ノードで使用可能な REST API UI を使用します。

.手順
. 接続に応じて、次のいずれかを実行します。
+
[cols="2*"]
|===
| オプション | 手順 


| 管理ノードに外部接続が必要です。  a| 
.. リポジトリの接続を確認します。
+
... 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
.... クラスタのユーザ名とパスワードを入力します。
.... クライアント ID を「 m node-client 」として入力します。
.... セッションを開始するには、 * Authorize * を選択します。
.... 承認ウィンドウを閉じます。


... REST API UI から、 * Get 気中 / パッケージ間の一時性 / リモートリポジトリ間の一時性 / 接続 * を選択します。
... [* 試してみてください * ] を選択します。
... [* Execute] を選択します。
... コード 200 が返された場合は、次の手順に進みます。リモートリポジトリへの接続がない場合は、接続を確立するか、ダークサイトのオプションを使用します。


.. アップグレードパッケージ ID を探します。
+
... REST API UI から * get/packages* を選択します。
... [* 試してみてください * ] を選択します。
... [* Execute] を選択します。
... 応答から、あとの手順で使用するためにパッケージ ID をコピーして保存します。






| 外部に接続されていないダークサイトに管理ノードが配置されている。  a| 
.. 管理ノードからアクセス可能なデバイスにストレージアップグレードパッケージをダウンロードします。 NetApp HCI ソフトウェアにアクセスします https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["ページをダウンロードします"^] して最新のストレージノードのイメージをダウンロードしてください。
.. ストレージアップグレードパッケージを管理ノードにアップロードします。
+
... 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
.... クラスタのユーザ名とパスワードを入力します。
.... クライアント ID を「 m node-client 」として入力します。
.... セッションを開始するには、 * Authorize * を選択します。
.... 承認ウィンドウを閉じます。


... REST API UI から * POST/packages * を選択します。
... [* 試してみてください * ] を選択します。
... [* Browse] を選択して、アップグレード・パッケージを選択します。
... 「 * Execute * 」を選択してアップロードを開始します。
... 応答から ' 後の手順で使用するためにパッケージ ID (`id"') をコピーして保存します


.. アップロードのステータスを確認します。
+
... REST API UI から、 * GEGET 処理対象 / パッケージ間の一時的なグループ / ｛ id ｝ 一時的なグループ / ステータス * を選択します。
... [* 試してみてください * ] を選択します。
... 前の手順でコピーしたパッケージ ID を * id * で入力します。
... ステータス要求を開始するには、 * Execute * を選択します。
+
応答が完了すると、「アクセス」として表示されます。





|===
. ストレージクラスタ ID を確認します。
+
.. 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアント ID を「 m node-client 」として入力します。
... セッションを開始するには、 * Authorize * を選択します。
... 承認ウィンドウを閉じます。


.. REST API UI から、 * GET / Installations * を選択します。
.. [* 試してみてください * ] を選択します。
.. [* Execute] を選択します。
.. 応答から、インストールアセット ID （「 id 」）をコピーします。
.. REST API UI から、 * GET / Installations / ｛ id ｝ * を選択します。
.. [* 試してみてください * ] を選択します。
.. インストールアセット ID を *id* フィールドに貼り付けます。
.. [* Execute] を選択します。
.. 応答から ' 後の手順で使用できるようにアップグレードするクラスタのストレージ・クラスタ ID （ ID ）をコピーして保存します


. ストレージのアップグレードを実行します。
+
.. 管理ノードでストレージ REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
... クラスタのユーザ名とパスワードを入力します。
... クライアント ID を「 m node-client 」として入力します。
... セッションを開始するには、 * Authorize * を選択します。
... 承認ウィンドウを閉じます。


.. [*POST/upgrade*] を選択します。
.. [* 試してみてください * ] を選択します。
.. パラメータフィールドにアップグレードパッケージ ID を入力します。
.. パラメータフィールドにストレージクラスタ ID を入力します。
+
ペイロードは次の例のようになります。

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. アップグレードを開始するには、 * Execute * を選択します。
+
応答は状態を「 initializing 」と示します。

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. 応答の一部であるアップグレード ID （「 upgradeId 」）をコピーします。


. アップグレードの進捗状況と結果を確認します。
+
.. Get Sebring/upgrades/｛ upgradeId ｝ * を選択します。
.. [* 試してみてください * ] を選択します。
.. アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
.. [* Execute] を選択します。
.. アップグレード中に問題または特別な要件が発生した場合は、次のいずれかを実行します。
+
[cols="2*"]
|===
| オプション | 手順 


| 応答の本文に「 failedHealthCheckks 」というメッセージが表示されているため、クラスタのヘルスの問題を修正する必要があります。  a| 
... 各問題について記載されている特定の技術情報アーティクルに移動するか、指定された対処方法を実行します。
... KB を指定した場合は、関連する技術情報アーティクルに記載されているプロセスを完了します。
... クラスタの問題を解決したら、必要に応じて再認証し、 * PUT 処理の際に必要な数 / アップグレード / ｛ upgradeId ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
... リクエスト本文に「 action 」 : 「 resume 」と入力します。
+
[listing]
----
{
  "action": "resume"
}
----
... [* Execute] を選択します。




| メンテナンス時間が終了しているか別の理由で、アップグレードを一時停止する必要があります。  a| 
... 必要に応じて再認証し、 * PUT に成功 / アップグレード / ｛ upgradeId ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
... リクエスト本文に「 action 」 : 「 pause 」と入力します。
+
[listing]
----
{
  "action": "pause"
}
----
... [* Execute] を選択します。




| 11.8 より前のバージョンの Element を実行している H610S クラスタをアップグレードする場合は、応答の本文に状態「 finishedNeedsAck 」が表示されます。H610Sストレージノードごとに、追加のアップグレード手順を実行する必要があります。  a| 
... このに記載されている追加のアップグレード手順を実行します https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["こちらの技術情報アーティクル"^] をクリックします。
... 必要に応じて再認証し、 * PUT に成功 / アップグレード / ｛ upgradeId ｝ * を選択します。
... [* 試してみてください * ] を選択します。
... アップグレード ID は、前の手順のアップグレード ID として * upgradeId * と入力します。
... リクエスト本文に「 action 」：「 acknowledge 」と入力します。
+
[listing]
----
{
  "action": "acknowledge"
}
----
... [* Execute] を選択します。


|===
.. 必要に応じて、処理が完了するまで * Get Theple/upgrades/｛ upgradeId ｝ * API を複数回実行します。
+
アップグレード中、エラーが発生しなかった場合、「ステータス」は「実行中」を示します。各ノードがアップグレードされると 'tep' の値が NodeFinished に変わります

+
アップグレードが正常に終了したのは 'percent` の値が '100' で 'tate' が 'finished' である場合です







== NetApp Hybrid Cloud を使用してアップグレードに失敗した場合の動作 制御

アップグレード中にドライブまたはノードで障害が発生した場合は、 Element UI にクラスタエラーが表示されます。アップグレードプロセスは次のノードに進まず、クラスタの障害が解決するまで待機します。UI の進捗状況バーには、アップグレードがクラスタの障害の解決を待機していることが表示されます。アップグレードはクラスタが正常に完了するまで待機するため、この段階で UI で * Pause * を選択することはできません。障害の調査に役立てるには、ネットアップサポートに問い合わせる必要があります。

NetApp Hybrid Cloud Control には 3 時間の待機時間があらかじめ設定されています。この時間内に、次のいずれかの状況が発生する可能性があります。

* クラスタの障害は 3 時間以内に解決され、アップグレードが再開されます。このシナリオでは対処は必要ありません。
* 問題は 3 時間後も解消されず、アップグレードのステータスが「 Error 」（エラー）と赤のバナーを表示します。問題が解決したら、「 * Resume 」（続行）を選択してアップグレードを再開できます。
* 3 時間以内に対処するために、アップグレードを一時的に中止する必要があることがネットアップサポートによって確認されました。サポートは API を使用してアップグレードを中止します。



CAUTION: ノードの更新中にクラスタのアップグレードを中止すると、そのノードからドライブが強制的に削除されることがあります。ドライブが強制的に削除された場合、ネットアップサポートに依頼して手動でドライブを元に戻す処理がアップグレード時に必要になります。ノードでファームウェアの更新や更新後の同期処理に時間がかかる可能性があります。アップグレードが停止していると思われる場合は、ネットアップサポートにお問い合わせください。

[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

